version: 0.2

phases:
  install: 
    commands:
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - echo GOPATH - $GOPATH
      - echo GOROOT - $GOROOT
  build:
    commands:
      - echo Build started on `date`
      - echo Getting packages
      - go get ./...
      - echo Compiling the Go code...
      - go build hello-world/main.go 
      # Package our application with AWS SAM
      # - aws cloudformation package --template-file template.yml --s3-bucket ${S3_BUCKET} --output-template-file packaged.yml
      # - aws cloudformation package --template-file template.yml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file packaged.yml
      # - aws cloudformation package --template-file template.yaml --s3-bucket codepipeline-us-east-1-675721587921 --output-template-file packaged.yaml
      - aws cloudformation package --template-file template.yaml --s3-bucket sam-pf2019 --output-template-file packaged.yaml
  post_build:
    commands:
      - echo Build completed on `date`
      - ls hello-world
artifacts:
  files:
    - hello-world/hello-world
    - packaged.yml


